version: '3.8'

services:
  vue-dev:
    build: .
    container_name: vue-dev  # Explicit name lebih baik
    # command: npm run dev -- --host
    volumes:
      - .:/app              # Mount seluruh folder
      - /app/node_modules # Untuk menghindari masalah dengan node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vue-dev.rule=Host(`vue.starter.localhost`)"
      - "traefik.http.routers.vue-dev.entrypoints=websecure"
      - "traefik.http.routers.vue-dev.tls=true"
      - "traefik.http.routers.vue-dev.service=vue-dev"
      - "traefik.http.routers.vue-dev.middlewares=websocket-headers@file"
      - "traefik.http.services.vue-dev.loadbalancer.server.port=5173"  
    networks:
      - vueapp_network
    ports:
      - "5173:5173"  # Untuk development access langsung

networks:
  vueapp_network:
    external: true